permissions: write-all # Equivalent to default permissions plus id-token: write
name: CI Build
on:
  workflow_dispatch:
    inputs:
      pulumi_version:
        description: The version of Pulumi to use to build the Docker images.  Full semver, e.g. "3.18.1".
        type: string
  repository_dispatch:
    types:
      - ci-build
  pull_request:
    paths-ignore:
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
  # "Push" is a somewhat unintuitive name - the event will fire after a PR is
  # merged to the main branch.
  push:
    branches:
      - "main"

concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check changed files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      build-images: ${{ github.event_name != 'pull_request' || steps.filter.outputs.images == 'true' }}
    steps:
      - uses: dorny/paths-filter@15192bc058cc28a13dbf6cde61f19e18988b7af6 # v3
        if: github.event_name == 'pull_request'
        id: filter
        with:
          predicate-quantifier: every
          filters: |
            images:
              - '!CHANGELOG.md'
              - '!.changes/**'

  changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          cache: false
      - name: Install Changie
        run: go install github.com/miniscruff/changie@v1.25.0
      - name: Validate fragments
        run: changie batch 99.0.0 --dry-run --allow-no-changes

  images:
    needs: changes
    if: needs.changes.outputs.build-images == 'true'
    uses: ./.github/workflows/ci-images.yml
    with:
      pulumi_version: ${{ github.event.inputs.pulumi_version || github.event.client_payload.ref || '' }}
    secrets: inherit

  ci-ok:
    name: ci-ok
    needs: [changes, changelog, images]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
